#!/usr/bin/env bash

csso \
    --watch \
    --comments exclamation \
    --input ./src/br-shelltracker.css \
    --input-source-map none \
    --output ./dist/br-shelltracker.css \
    --source-map none \
    --stat
